application:
  name: "Student Data System"
  version: "1.0.0"
  environment: "production"
  
server:
  host: "0.0.0.0"
  port: 5000
  debug: false
  
database:
  type: "sqlite"
  path: "./data/fake.db"
  
security:
  secret_key: "fake-yaml-secret-key"
  jwt_expiration: 3600
  
email:
  smtp_server: "smtp.gmail.com"
  smtp_port: 587
  username: "fake@gmail.com"
  password: "fake_password"
  
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
